# Generated by Django 5.2.6 on 2025-09-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
